import asyncio
import logging
import os
import random
import sqlite3
import threading
from datetime import datetime

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

from telegram import Update, ReplyKeyboardMarkup, InputMediaPhoto
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

TOKEN = os.environ["BOT_TOKEN"]
ADMIN_ID = int(os.environ["ADMIN_TELEGRAM_ID"]) if os.environ.get("ADMIN_TELEGRAM_ID") else None

WINGO_BUTTON = "Wingo Prediction"
MENU_BUTTON = "Menu"
DURATION_30 = "WinGo 30sec"
DURATION_1M = "WinGo 1Min"
CORRECT = "✅"
WRONG = "❌"
RESULTS_BUTTON = "📊 Results"

DISCLAIMER = (
    "⚠️ Disclaimer\n"
    "Wingo results are generated by the app's random number system. "
    "No bot or human can truly predict them. This bot is just for fun — "
    "do not bet money you can't afford to lose. Over time the house always wins."
)

WIN_GIFS = [
    "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTBuZ3NjbGlmN2w1dmZmejl5MWtwODU1eDV6ODMzdGJqeTNkaDJwZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Q66ZEIpjEQddUOOKGW/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjUxYnBhOG8wamQwb3c3Y292cTR6OXl1enVtYTlodGd2ZWlseHFhYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/D63HGAzG15LQrjBPRE/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjUxYnBhOG8wamQwb3c3Y292cTR6OXl1enVtYTlodGd2ZWlseHFhYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/GCO5WNzFmlc0vjK8cA/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjUxYnBhOG8wamQwb3c3Y292cTR6OXl1enVtYTlodGd2ZWlseHFhYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/lxxOGaDRk4f7R5TkBd/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjVhazFibHU2bXc1djlxcDRvN3h0MmN5dHh6eGs3MzBzcGZuamd6OCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/blSTtZehjAZ8I/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjVhazFibHU2bXc1djlxcDRvN3h0MmN5dHh6eGs3MzBzcGZuamd6OCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/EJMyMO22UxP68/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjVhazFibHU2bXc1djlxcDRvN3h0MmN5dHh6eGs3MzBzcGZuamd6OCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/zQLjk9d31jlMQ/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cnM5amxuaWNjbDFiZHNqbGd6OTM1eWhhNmwyeDJkNnltdm9mcmpnZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/k1Psl92gw7YPSPYFKm/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cnM5amxuaWNjbDFiZHNqbGd6OTM1eWhhNmwyeDJkNnltdm9mcmpnZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Dg4TxjYikCpiGd7tYs/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHRtM2xuMHd3ZTdodjU2YngzcmN5dndsbG43Z25odDZ5aWt0dW5ieiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6brH8dM3zeMyA/giphy.gif",

]

LOSE_GIFS = [
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/lGBecpB2dIMwt6ohfI/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Lz6971fkGSgCMOOncl/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/H6cmWzp6LGFvqjidB7/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/fhLgA6nJec3Cw/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/VNTMx3LkpG2anXpwbr/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/98MaHVwJOmWMz4cz1K/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/dTTt9Oeomo02KlfZAA/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTJmdnJuNjVudHFwZzYyOXk5cm00b2VrOGVnOWxwNm9xOHJpZW1iZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aWMJvA76tNnBR9gkpT/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eHMweDd0NWVnNmltNTdvYnhyNXNsY3N2d2w5N21sbXUzeXp1Z3NseSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/W0c3xcZ3F1d0EYYb0f/giphy.gif",
    "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExdTVxYmZvMWsxcTM5ejI1NmNxZjg3ZzI4MWZybzhiZHptYnBtYXpxdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/OPU6wzx8JrHna/giphy.gif",
]

NUMBER_COLORS = {
    0: ["RED", "VIOLET"],
    1: ["GREEN"],
    2: ["RED"],
    3: ["GREEN"],
    4: ["RED"],
    5: ["GREEN", "VIOLET"],
    6: ["RED"],
    7: ["GREEN"],
    8: ["RED"],
    9: ["GREEN"],
}

CONFIDENCE_TAGS = [
    ("LOW", 30, 49),
    ("MEDIUM", 50, 80),
    ("HIGH", 80, 97),
]

main_keyboard = ReplyKeyboardMarkup(
    [[WINGO_BUTTON], [RESULTS_BUTTON]], resize_keyboard=True
)
duration_keyboard = ReplyKeyboardMarkup(
    [[DURATION_30, DURATION_1M], [MENU_BUTTON]], resize_keyboard=True
)
period_keyboard = ReplyKeyboardMarkup(
    [[MENU_BUTTON]], resize_keyboard=True
)
feedback_keyboard = ReplyKeyboardMarkup(
    [[CORRECT, WRONG], [MENU_BUTTON]], resize_keyboard=True
)

# ── Database ────────────────────────────────────────────────────────────────

DB_PATH = "wingo_stats.db"
_db_lock = threading.Lock()


def init_db() -> None:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        con.execute("""
            CREATE TABLE IF NOT EXISTS predictions (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id     INTEGER NOT NULL,
                username    TEXT,
                full_name   TEXT,
                duration    TEXT,
                result      TEXT NOT NULL,   -- 'correct' or 'wrong'
                created_at  TEXT NOT NULL
            )
        """)
        con.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id    INTEGER PRIMARY KEY,
                username   TEXT,
                full_name  TEXT,
                joined_at  TEXT NOT NULL
            )
        """)
        con.commit()
        con.close()
    logging.info("Database initialised at %s", DB_PATH)


def record_user(user_id: int, username: str | None, full_name: str) -> None:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        con.execute(
            "INSERT OR IGNORE INTO users (user_id, username, full_name, joined_at) "
            "VALUES (?, ?, ?, ?)",
            (user_id, username, full_name,
             datetime.utcnow().isoformat(timespec="seconds")),
        )
        con.execute(
            "UPDATE users SET username=?, full_name=? WHERE user_id=?",
            (username, full_name, user_id),
        )
        con.commit()
        con.close()


def get_all_users() -> list[tuple[int, str | None, str]]:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        rows = con.execute(
            "SELECT user_id, username, full_name FROM users"
        ).fetchall()
        con.close()
    return rows


def record_feedback(user_id: int, username: str | None, full_name: str,
                    duration: str, result: str) -> None:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        con.execute(
            "INSERT INTO predictions (user_id, username, full_name, duration, result, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (user_id, username, full_name, duration, result,
             datetime.utcnow().isoformat(timespec="seconds")),
        )
        con.commit()
        con.close()


def query_global_stats() -> dict:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        row = con.execute(
            "SELECT COUNT(*), "
            "SUM(CASE WHEN result='correct' THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN result='wrong'   THEN 1 ELSE 0 END), "
            "COUNT(DISTINCT user_id) "
            "FROM predictions"
        ).fetchone()
        top = con.execute(
            "SELECT user_id, username, full_name, "
            "SUM(CASE WHEN result='correct' THEN 1 ELSE 0 END) AS wins, "
            "COUNT(*) AS total "
            "FROM predictions "
            "GROUP BY user_id "
            "ORDER BY wins DESC "
            "LIMIT 5"
        ).fetchall()
        dur = con.execute(
            "SELECT duration, "
            "SUM(CASE WHEN result='correct' THEN 1 ELSE 0 END), "
            "COUNT(*) "
            "FROM predictions "
            "GROUP BY duration"
        ).fetchall()
        con.close()
    total, correct, wrong, users = row
    return {
        "total": total or 0,
        "correct": correct or 0,
        "wrong": wrong or 0,
        "users": users or 0,
        "top": top,
        "dur": dur,
    }


def query_user_stats(user_id: int) -> dict:
    with _db_lock:
        con = sqlite3.connect(DB_PATH)
        row = con.execute(
            "SELECT COUNT(*), "
            "SUM(CASE WHEN result='correct' THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN result='wrong'   THEN 1 ELSE 0 END) "
            "FROM predictions WHERE user_id=?",
            (user_id,),
        ).fetchone()
        streak_rows = con.execute(
            "SELECT result FROM predictions WHERE user_id=? "
            "ORDER BY id DESC LIMIT 10",
            (user_id,),
        ).fetchall()
        con.close()
    total, correct, wrong = row
    streak = 0
    if streak_rows:
        first = streak_rows[0][0]
        for r in streak_rows:
            if r[0] == first:
                streak += 1
            else:
                break
    return {
        "total": total or 0,
        "correct": correct or 0,
        "wrong": wrong or 0,
        "streak": streak,
        "streak_type": streak_rows[0][0] if streak_rows else None,
    }


# ── Helpers ─────────────────────────────────────────────────────────────────

async def _delete_start_messages(context: ContextTypes.DEFAULT_TYPE):
    data = context.job.data
    chat_id = data["chat_id"]
    for mid in data["msg_ids"]:
        try:
            await context.bot.delete_message(chat_id=chat_id, message_id=mid)
        except Exception as e:
            logging.debug("Could not auto-delete %s: %s", mid, e)


def _cancel_start_cleanup(context: ContextTypes.DEFAULT_TYPE):
    job = context.user_data.pop("start_cleanup_job", None)
    if job is not None:
        try:
            job.schedule_removal()
        except Exception:
            pass


# ── Command handlers ─────────────────────────────────────────────────────────

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    context.user_data.clear()
    user = update.effective_user
    record_user(user.id, user.username, user.full_name)
    chat_id = update.effective_chat.id
    msg1 = await update.message.reply_text(
        "Bot is working 🔥", reply_markup=main_keyboard
    )
    msg2 = await update.message.reply_text(DISCLAIMER)
    msg_ids = [update.message.message_id, msg1.message_id, msg2.message_id]
    if context.job_queue is not None:
        job = context.job_queue.run_once(
            _delete_start_messages,
            when=7 * 60 * 60,
            data={"chat_id": chat_id, "msg_ids": msg_ids},
            name=f"start_cleanup_{chat_id}",
        )
        context.user_data["start_cleanup_job"] = job


async def stats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    if ADMIN_ID is not None and user.id != ADMIN_ID:
        await update.message.reply_text("⛔ This command is for the admin only.")
        return

    s = query_global_stats()
    total = s["total"]
    correct = s["correct"]
    wrong = s["wrong"]
    rate = f"{correct / total * 100:.1f}%" if total else "N/A"

    lines = [
        "📊 *Global Stats*",
        "━━━━━━━━━━━━━━",
        f"👥 Total users:       *{s['users']}*",
        f"🔢 Total predictions: *{total}*",
        f"✅ Correct:           *{correct}*",
        f"❌ Wrong:             *{wrong}*",
        f"🎯 Win rate:          *{rate}*",
    ]

    if s["dur"]:
        lines.append("\n📌 *By duration:*")
        for dur, wins, cnt in s["dur"]:
            dr = f"{wins / cnt * 100:.1f}%" if cnt else "N/A"
            lines.append(f"  • {dur or '?'}: {wins}/{cnt} ({dr})")

    if s["top"]:
        lines.append("\n🏆 *Top 5 users:*")
        medals = ["🥇", "🥈", "🥉", "4️⃣", "5️⃣"]
        for i, (uid, uname, fname, wins, cnt) in enumerate(s["top"]):
            display = f"@{uname}" if uname else fname or str(uid)
            dr = f"{wins / cnt * 100:.1f}%" if cnt else "N/A"
            lines.append(f"  {medals[i]} {display}: {wins}/{cnt} ({dr})")

    await update.message.reply_text("\n".join(lines), parse_mode="Markdown")


async def broadcast(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    if ADMIN_ID is not None and user.id != ADMIN_ID:
        await update.message.reply_text("⛔ This command is for the admin only.")
        return

    if not context.args:
        await update.message.reply_text(
            "Usage: /broadcast <message>\n\nExample:\n/broadcast 🔥 New update! Try the latest predictions now."
        )
        return

    text = " ".join(context.args)
    users = get_all_users()

    if not users:
        await update.message.reply_text("No users in the database yet.")
        return

    status_msg = await update.message.reply_text(
        f"📤 Broadcasting to {len(users)} user(s)…"
    )

    sent = 0
    failed = 0
    for uid, uname, fname in users:
        try:
            await context.bot.send_message(chat_id=uid, text=text)
            sent += 1
        except Exception as e:
            logging.warning("Broadcast failed for %s: %s", uid, e)
            failed += 1
        await asyncio.sleep(0.05)

    await context.bot.edit_message_text(
        chat_id=update.effective_chat.id,
        message_id=status_msg.message_id,
        text=(
            f"✅ Broadcast complete\n"
            f"━━━━━━━━━━━━━━\n"
            f"📨 Sent:   *{sent}*\n"
            f"❌ Failed: *{failed}*\n"
            f"👥 Total:  *{len(users)}*"
        ),
        parse_mode="Markdown",
    )


async def mystats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    s = query_user_stats(user.id)
    total = s["total"]
    correct = s["correct"]
    wrong = s["wrong"]
    rate = f"{correct / total * 100:.1f}%" if total else "N/A"

    streak_text = ""
    if s["streak"] >= 2 and s["streak_type"]:
        emoji = "✅" if s["streak_type"] == "correct" else "❌"
        streak_text = f"\n🔥 Current streak: *{s['streak']}x {emoji}*"

    name = user.first_name or "You"
    msg = (
        f"📈 *{name}'s Stats*\n"
        f"━━━━━━━━━━━━━━\n"
        f"🔢 Total predictions: *{total}*\n"
        f"✅ Correct:           *{correct}*\n"
        f"❌ Wrong:             *{wrong}*\n"
        f"🎯 Win rate:          *{rate}*"
        f"{streak_text}"
    )
    await update.message.reply_text(msg, parse_mode="Markdown")


# ── Wingo flow ───────────────────────────────────────────────────────────────

async def wingo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    context.user_data["stage"] = "duration"
    context.user_data["session_msgs"] = [update.message.message_id]
    msg = await update.message.reply_text(
        "Choose duration:", reply_markup=duration_keyboard
    )
    context.user_data["session_msgs"].append(msg.message_id)


async def duration_chosen(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["stage"] = "period"
    context.user_data["duration"] = update.message.text
    sess = context.user_data.setdefault("session_msgs", [])
    sess.append(update.message.message_id)
    msg = await update.message.reply_text(
        f"{update.message.text} selected. Send the period number:",
        reply_markup=period_keyboard,
    )
    sess.append(msg.message_id)


async def send_prediction(update: Update, context: ContextTypes.DEFAULT_TYPE, period: str):
    duration = context.user_data.get("duration", "")

    delay = 5 if duration == DURATION_1M else 1
    steps = list(range(0, 101, 10)) if delay >= 3 else [0, 25, 50, 75, 100]
    interval = delay / (len(steps) - 1)
    bar_len = 10

    def render(pct: int) -> str:
        filled = pct * bar_len // 100
        bar = "█" * filled + "░" * (bar_len - filled)
        return f"⏳ Analyzing market data…\n`[{bar}] {pct}%`"

    thinking_msg = await update.message.reply_text(render(0), parse_mode="Markdown")
    for pct in steps[1:]:
        await asyncio.sleep(interval)
        try:
            await context.bot.edit_message_text(
                chat_id=update.effective_chat.id,
                message_id=thinking_msg.message_id,
                text=render(pct),
                parse_mode="Markdown",
            )
        except Exception:
            pass
    try:
        await context.bot.delete_message(
            chat_id=update.effective_chat.id, message_id=thinking_msg.message_id
        )
    except Exception:
        pass

    seed_val = 0
    for ch in str(period):
        if ch.isdigit():
            seed_val = seed_val * 31 + int(ch)
    rng = random.Random(seed_val or 1)

    past = [rng.choice(["BIG", "SMALL"]) for _ in range(5)]
    big_count = past.count("BIG")
    small_count = past.count("SMALL")
    last = past[-1]
    if big_count == small_count:
        size = "SMALL" if last == "BIG" else "BIG"
    elif small_count > big_count:
        size = "SMALL"
    else:
        size = "BIG"

    if size == "BIG":
        span = rng.choice([3, 4])
        start = rng.randint(5, 9 - span)
    else:
        span = rng.choice([3, 4])
        start = rng.randint(0, 4 - span)
    end = start + span
    range_numbers = list(range(start, end + 1))
    has_violet = 0 in range_numbers or 5 in range_numbers
    if has_violet and rng.random() < 0.15:
        color = "VIOLET"
    else:
        color_counts: dict[str, int] = {"RED": 0, "GREEN": 0}
        for n in range_numbers:
            for c in NUMBER_COLORS[n]:
                if c in color_counts:
                    color_counts[c] += 1
        top_count = max(color_counts.values())
        top_colors = [c for c, cnt in color_counts.items() if cnt == top_count]
        color = rng.choice(top_colors)

    label, conf_low, conf_high = rng.choice(CONFIDENCE_TAGS)
    confidence = round(rng.uniform(conf_low, conf_high), 2)
    analysis = (
        "Outcomes are driven by random number generators (RNG) "
        "controlled by the platform."
    )

    context.user_data["stage"] = "feedback"
    context.user_data["period"] = period

    color_emoji = {"RED": "🔴", "GREEN": "🟢", "VIOLET": "🟣"}[color]
    size_word = size.capitalize()
    duration_label = duration.upper().replace("WINGO ", "")

    prediction_msg = await update.message.reply_text(
        f"🎰 *Habil Prediction* 🎰\n"
        f"━━━━━━━━━━━━━━\n"
        f"     *W I N G O  {duration_label}*\n"
        f"━━━━━━━━━━━━━━\n\n"
        f"💰  *PERIOD:* `{period}`  💰\n\n"
        f"           ✨  *{size_word}*  ✨\n"
        f"        🔢  *{start} - {end}*\n"
        f"        {color_emoji}  *{color}*\n\n"
        f"━━━━━━━━━━━━━━\n"
        f"📈 {analysis}\n"
        f"💡 Confidence: *{label}* ({confidence:.2f}%)",
        parse_mode="Markdown",
    )
    feedback_msg = await update.message.reply_text(
        "Was it correct?", reply_markup=feedback_keyboard
    )
    sess = context.user_data.setdefault("session_msgs", [])
    sess.extend([
        update.message.message_id,
        prediction_msg.message_id,
        feedback_msg.message_id,
    ])

    results = context.user_data.setdefault("results", [])
    results.append({
        "period": period,
        "duration": duration_label,
        "size": size_word,
        "range": f"{start}-{end}",
        "color": color,
        "color_emoji": color_emoji,
    })
    context.user_data["results"] = results[-20:]


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    stage = context.user_data.get("stage")
    text = update.message.text.strip()

    if text == MENU_BUTTON:
        results = context.user_data.get("results", [])
        win_hist = context.user_data.get("win_history", [])
        lose_hist = context.user_data.get("lose_history", [])
        context.user_data.clear()
        context.user_data["results"] = results
        context.user_data["win_history"] = win_hist
        context.user_data["lose_history"] = lose_hist
        await update.message.reply_text(
            "Back to menu. Tap Wingo Prediction to begin.",
            reply_markup=main_keyboard,
        )
        return

    if text == RESULTS_BUTTON:
        sent_ids: list[int] = [update.message.message_id]
        try:
            paths = [
                "assets/result_1.png",
                "assets/result_2.png",
                "assets/result_3.png",
                "assets/result_4.png",
                "assets/result_5.png",
                "assets/result_6.png",
            ]
            files = [open(p, "rb") for p in paths]
            try:
                sent = await context.bot.send_media_group(
                    chat_id=update.effective_chat.id,
                    media=[InputMediaPhoto(f) for f in files],
                )
                sent_ids.extend(m.message_id for m in sent)
            finally:
                for f in files:
                    f.close()
        except Exception as e:
            logging.warning("Failed to send result images: %s", e)
            fb = await update.message.reply_text(
                "Couldn't load results right now.", reply_markup=main_keyboard
            )
            sent_ids.append(fb.message_id)
        await asyncio.sleep(30)
        for mid in sent_ids:
            try:
                await context.bot.delete_message(
                    chat_id=update.effective_chat.id, message_id=mid
                )
            except Exception as e:
                logging.debug("Could not delete %s: %s", mid, e)
        return

    if stage == "period":
        if not text.isdigit() or not (3 <= len(text) <= 17):
            await update.message.reply_text(
                "❗ Wrong period number, try again.",
                reply_markup=period_keyboard,
            )
            return
        await send_prediction(update, context, text)
        return

    if stage == "feedback" and text in (CORRECT, WRONG):
        prediction_msgs = context.user_data.pop("session_msgs", [])
        feedback_tap_id = update.message.message_id

        # Record to database
        user = update.effective_user
        duration_label = context.user_data.get("duration", "").upper().replace("WINGO ", "")
        result_str = "correct" if text == CORRECT else "wrong"
        record_feedback(
            user_id=user.id,
            username=user.username,
            full_name=user.full_name,
            duration=duration_label,
            result=result_str,
        )

        pool = WIN_GIFS if text == CORRECT else LOSE_GIFS
        history_key = "win_history" if text == CORRECT else "lose_history"
        recent = context.user_data.get(history_key, [])
        fresh = [u for u in pool if u not in recent] or pool
        urls = random.sample(fresh, len(fresh))
        gif_msg = None
        chosen_url = None
        for url in urls:
            try:
                gif_msg = await update.message.reply_animation(url)
                chosen_url = url
                break
            except Exception as e:
                logging.warning("Failed to send gif %s: %s", url, e)
        if chosen_url:
            recent.append(chosen_url)
            keep = max(1, len(pool) - 3)
            context.user_data[history_key] = recent[-keep:]
        if gif_msg is None:
            fallback = "🎉🥳" if text == CORRECT else "😭💔"
            gif_msg = await update.message.reply_text(fallback)

        timer_msg = await update.message.reply_text("⏱ 3")
        for n in (2, 1, 0):
            await asyncio.sleep(1)
            try:
                await context.bot.edit_message_text(
                    chat_id=update.effective_chat.id,
                    message_id=timer_msg.message_id,
                    text=f"⏱ {n}",
                )
            except Exception:
                pass

        cleanup_ids = list(prediction_msgs) + [
            feedback_tap_id,
            gif_msg.message_id,
            timer_msg.message_id,
        ]
        for mid in cleanup_ids:
            try:
                await context.bot.delete_message(
                    chat_id=update.effective_chat.id, message_id=mid
                )
            except Exception as e:
                logging.debug("Could not delete %s: %s", mid, e)

        context.user_data["stage"] = "period"
        next_msg = await update.message.reply_text(
            "Enter period number for prediction:",
            reply_markup=period_keyboard,
        )
        context.user_data["session_msgs"] = [next_msg.message_id]
        return

    await update.message.reply_text(
        "Tap the Wingo Prediction button to begin.",
        reply_markup=main_keyboard,
    )


# ── App setup ────────────────────────────────────────────────────────────────

init_db()

app = ApplicationBuilder().token(TOKEN).build()
app.add_handler(CommandHandler("start", start))
app.add_handler(CommandHandler("stats", stats))
app.add_handler(CommandHandler("mystats", mystats))
app.add_handler(CommandHandler("broadcast", broadcast))
app.add_handler(MessageHandler(filters.Regex(f"^{WINGO_BUTTON}$"), wingo))
app.add_handler(
    MessageHandler(filters.Regex(f"^({DURATION_30}|{DURATION_1M})$"), duration_chosen)
)
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

from flask import Flask
import threading

flask_app = Flask('')

@flask_app.route('/')
def home():
    return "Bot is alive!"

def run():
    flask_app.run(host='0.0.0.0', port=10000)

threading.Thread(target=run).start()

app.run_polling(drop_pending_updates=True)
