import asyncio
import logging
import random

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

from telegram import Update, ReplyKeyboardMarkup, ReplyKeyboardRemove, InputMediaPhoto
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

TOKEN = "8761847605:AAEQNNCaGEyXiTlGWrA_rgtv6UqSfMQ2ljo"

WINGO_BUTTON = "Wingo Prediction"
MENU_BUTTON = "Menu"
DURATION_30 = "WinGo 30sec"
DURATION_1M = "WinGo 1Min"
CORRECT = "✅"
WRONG = "❌"
RESULTS_BUTTON = "📊 Results"

DISCLAIMER = (
    "⚠️ Disclaimer\n"
    "Wingo results are generated by the app's random number system. "
    "No bot or human can truly predict them. This bot is just for fun — "
    "do not bet money you can't afford to lose. Over time the house always wins."
)

WIN_GIFS = [
    "https://media.giphy.com/media/3o7TKr3nzbh5WgCFxe/giphy.gif",
    "https://media.giphy.com/media/QBd2kLB5qDmysEXre9/giphy.gif",
    "https://media.giphy.com/media/MT5UUV1d4CXE2A37Dg/giphy.gif",
    "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",
    "https://media.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif",
    "https://media.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif",
]

LOSE_GIFS = [
    "https://media.giphy.com/media/L95W4wv8nnb9K/giphy.gif",
    "https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif",
    "https://media.giphy.com/media/ROF8OQvDmxytW/giphy.gif",
    "https://media.giphy.com/media/OPU6wzx8JrHna/giphy.gif",
    "https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif",
]

NUMBER_COLORS = {
    0: ["RED", "VIOLET"],
    1: ["GREEN"],
    2: ["RED"],
    3: ["GREEN"],
    4: ["RED"],
    5: ["GREEN", "VIOLET"],
    6: ["RED"],
    7: ["GREEN"],
    8: ["RED"],
    9: ["GREEN"],
}

ANALYSIS_LINES = [
    "Last 5 periods showed a {bias} bias.",
    "Trend leaning {bias} side after recent streak.",
    "Pattern break expected — {bias} likely.",
    "Heatmap shows {bias} numbers cooling down.",
    "Cycle analysis suggests {bias} continuation.",
    "Volume distribution favoring {bias} this round.",
]

CONFIDENCE_TAGS = [
    ("LOW", 30, 49),
    ("MEDIUM", 50, 80),
    ("HIGH", 80, 97),
]

main_keyboard = ReplyKeyboardMarkup(
    [[WINGO_BUTTON], [RESULTS_BUTTON]], resize_keyboard=True
)
duration_keyboard = ReplyKeyboardMarkup(
    [[DURATION_30, DURATION_1M], [MENU_BUTTON]], resize_keyboard=True
)
period_keyboard = ReplyKeyboardMarkup(
    [[MENU_BUTTON]], resize_keyboard=True
)
feedback_keyboard = ReplyKeyboardMarkup(
    [[CORRECT, WRONG], [MENU_BUTTON]], resize_keyboard=True
)


async def _delete_start_messages(context: ContextTypes.DEFAULT_TYPE):
    data = context.job.data
    chat_id = data["chat_id"]
    for mid in data["msg_ids"]:
        try:
            await context.bot.delete_message(chat_id=chat_id, message_id=mid)
        except Exception as e:
            logging.debug("Could not auto-delete %s: %s", mid, e)


def _cancel_start_cleanup(context: ContextTypes.DEFAULT_TYPE):
    job = context.user_data.pop("start_cleanup_job", None)
    if job is not None:
        try:
            job.schedule_removal()
        except Exception:
            pass


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    context.user_data.clear()
    chat_id = update.effective_chat.id
    msg1 = await update.message.reply_text(
        "Bot is working 🔥", reply_markup=main_keyboard
    )
    msg2 = await update.message.reply_text(DISCLAIMER)
    msg_ids = [update.message.message_id, msg1.message_id, msg2.message_id]
    if context.job_queue is not None:
        job = context.job_queue.run_once(
            _delete_start_messages,
            when=7 * 60 * 60,
            data={"chat_id": chat_id, "msg_ids": msg_ids},
            name=f"start_cleanup_{chat_id}",
        )
        context.user_data["start_cleanup_job"] = job


async def wingo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    context.user_data["stage"] = "duration"
    context.user_data["session_msgs"] = [update.message.message_id]
    msg = await update.message.reply_text(
        "Choose duration:", reply_markup=duration_keyboard
    )
    context.user_data["session_msgs"].append(msg.message_id)


async def duration_chosen(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data["stage"] = "period"
    context.user_data["duration"] = update.message.text
    sess = context.user_data.setdefault("session_msgs", [])
    sess.append(update.message.message_id)
    msg = await update.message.reply_text(
        f"{update.message.text} selected. Send the period number:",
        reply_markup=period_keyboard,
    )
    sess.append(msg.message_id)


async def send_prediction(update: Update, context: ContextTypes.DEFAULT_TYPE, period: str):
    duration = context.user_data.get("duration", "")

    delay = 5 if duration == DURATION_1M else 1
    steps = list(range(0, 101, 10)) if delay >= 3 else [0, 25, 50, 75, 100]
    interval = delay / (len(steps) - 1)
    bar_len = 10

    def render(pct: int) -> str:
        filled = pct * bar_len // 100
        bar = "█" * filled + "░" * (bar_len - filled)
        return f"⏳ Analyzing market data…\n`[{bar}] {pct}%`"

    thinking_msg = await update.message.reply_text(render(0), parse_mode="Markdown")
    for pct in steps[1:]:
        await asyncio.sleep(interval)
        try:
            await context.bot.edit_message_text(
                chat_id=update.effective_chat.id,
                message_id=thinking_msg.message_id,
                text=render(pct),
                parse_mode="Markdown",
            )
        except Exception:
            pass
    try:
        await context.bot.delete_message(
            chat_id=update.effective_chat.id, message_id=thinking_msg.message_id
        )
    except Exception:
        pass

    seed_val = 0
    for ch in str(period):
        if ch.isdigit():
            seed_val = seed_val * 31 + int(ch)
    rng = random.Random(seed_val or 1)

    past = [rng.choice(["BIG", "SMALL"]) for _ in range(5)]
    big_count = past.count("BIG")
    small_count = past.count("SMALL")
    last = past[-1]
    if big_count == small_count:
        size = "SMALL" if last == "BIG" else "BIG"
        reason = (
            f"Big and Small are tied ({big_count}-{small_count}); "
            f"last was {last.lower()}, so flip predicted."
        )
    elif small_count > big_count:
        if last == "BIG":
            size = "SMALL"
            reason = (
                f"Small dominant ({small_count}-{big_count}); "
                f"last big tends to revert to small."
            )
        else:
            size = "SMALL"
            reason = (
                f"Small streak active ({small_count}-{big_count}); "
                f"trend continuation favored."
            )
    else:
        if last == "SMALL":
            size = "BIG"
            reason = (
                f"Big dominant ({big_count}-{small_count}); "
                f"last small tends to revert to big."
            )
        else:
            size = "BIG"
            reason = (
                f"Big streak active ({big_count}-{small_count}); "
                f"trend continuation favored."
            )

    if size == "BIG":
        span = rng.choice([3, 4])
        start = rng.randint(5, 9 - span)
    else:
        span = rng.choice([3, 4])
        start = rng.randint(0, 4 - span)
    end = start + span
    range_numbers = list(range(start, end + 1))
    has_violet = 0 in range_numbers or 5 in range_numbers
    if has_violet and rng.random() < 0.15:
        color = "VIOLET"
    else:
        color_counts: dict[str, int] = {"RED": 0, "GREEN": 0}
        for n in range_numbers:
            for c in NUMBER_COLORS[n]:
                if c in color_counts:
                    color_counts[c] += 1
        top_count = max(color_counts.values())
        top_colors = [c for c, cnt in color_counts.items() if cnt == top_count]
        color = rng.choice(top_colors)

    label, conf_low, conf_high = rng.choice(CONFIDENCE_TAGS)
    confidence = round(rng.uniform(conf_low, conf_high), 2)
    analysis = (
        "Outcomes are driven by random number generators (RNG) "
        "controlled by the platform."
    )

    context.user_data["stage"] = "feedback"
    context.user_data["period"] = period

    color_emoji = {"RED": "🔴", "GREEN": "🟢", "VIOLET": "🟣"}[color]
    size_word = size.capitalize()
    duration_label = duration.upper().replace("WINGO ", "")

    prediction_msg = await update.message.reply_text(
        f"🎰 *Habil Prediction* 🎰\n"
        f"━━━━━━━━━━━━━━\n"
        f"     *W I N G O  {duration_label}*\n"
        f"━━━━━━━━━━━━━━\n\n"
        f"💰  *PERIOD:* `{period}`  💰\n\n"
        f"           ✨  *{size_word}*  ✨\n"
        f"        🔢  *{start} - {end}*\n"
        f"        {color_emoji}  *{color}*\n\n"
        f"━━━━━━━━━━━━━━\n"
        f"📈 {analysis}\n"
        f"💡 Confidence: *{label}* ({confidence:.2f}%)",
        parse_mode="Markdown",
    )
    feedback_msg = await update.message.reply_text(
        "Was it correct?", reply_markup=feedback_keyboard
    )
    sess = context.user_data.setdefault("session_msgs", [])
    sess.extend([
        update.message.message_id,
        prediction_msg.message_id,
        feedback_msg.message_id,
    ])

    results = context.user_data.setdefault("results", [])
    results.append({
        "period": period,
        "duration": duration_label,
        "size": size_word,
        "range": f"{start}-{end}",
        "color": color,
        "color_emoji": color_emoji,
    })
    context.user_data["results"] = results[-20:]


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    _cancel_start_cleanup(context)
    stage = context.user_data.get("stage")
    text = update.message.text.strip()

    if text == MENU_BUTTON:
        results = context.user_data.get("results", [])
        win_hist = context.user_data.get("win_history", [])
        lose_hist = context.user_data.get("lose_history", [])
        context.user_data.clear()
        context.user_data["results"] = results
        context.user_data["win_history"] = win_hist
        context.user_data["lose_history"] = lose_hist
        await update.message.reply_text(
            "Back to menu. Tap Wingo Prediction to begin.",
            reply_markup=main_keyboard,
        )
        return

    if text == RESULTS_BUTTON:
        sent_ids: list[int] = [update.message.message_id]
        try:
            paths = [
                "assets/result_1.png",
                "assets/result_2.png",
                "assets/result_3.png",
                "assets/result_4.png",
                "assets/result_5.png",
                "assets/result_6.png",
            ]
            files = [open(p, "rb") for p in paths]
            try:
                sent = await context.bot.send_media_group(
                    chat_id=update.effective_chat.id,
                    media=[InputMediaPhoto(f) for f in files],
                )
                sent_ids.extend(m.message_id for m in sent)
            finally:
                for f in files:
                    f.close()
        except Exception as e:
            logging.warning("Failed to send result images: %s", e)
            fb = await update.message.reply_text(
                "Couldn't load results right now.", reply_markup=main_keyboard
            )
            sent_ids.append(fb.message_id)
        await asyncio.sleep(1)
        for mid in sent_ids:
            try:
                await context.bot.delete_message(
                    chat_id=update.effective_chat.id, message_id=mid
                )
            except Exception as e:
                logging.debug("Could not delete %s: %s", mid, e)
        return

    if stage == "period":
        if not text.isdigit() or not (3 <= len(text) <= 17):
            await update.message.reply_text(
                "❗ Wrong period number, try again.",
                reply_markup=period_keyboard,
            )
            return
        await send_prediction(update, context, text)
        return

    if stage == "feedback" and text in (CORRECT, WRONG):
        prediction_msgs = context.user_data.pop("session_msgs", [])
        feedback_tap_id = update.message.message_id

        pool = WIN_GIFS if text == CORRECT else LOSE_GIFS
        history_key = "win_history" if text == CORRECT else "lose_history"
        recent = context.user_data.get(history_key, [])
        fresh = [u for u in pool if u not in recent] or pool
        urls = random.sample(fresh, len(fresh))
        gif_msg = None
        chosen_url = None
        for url in urls:
            try:
                gif_msg = await update.message.reply_animation(url)
                chosen_url = url
                break
            except Exception as e:
                logging.warning("Failed to send gif %s: %s", url, e)
        if chosen_url:
            recent.append(chosen_url)
            keep = max(1, len(pool) - 3)
            context.user_data[history_key] = recent[-keep:]
        if gif_msg is None:
            fallback = "🎉🥳" if text == CORRECT else "😭💔"
            gif_msg = await update.message.reply_text(fallback)

        timer_msg = await update.message.reply_text("⏱ 3")
        for n in (2, 1, 0):
            await asyncio.sleep(1)
            try:
                await context.bot.edit_message_text(
                    chat_id=update.effective_chat.id,
                    message_id=timer_msg.message_id,
                    text=f"⏱ {n}",
                )
            except Exception:
                pass

        cleanup_ids = list(prediction_msgs) + [
            feedback_tap_id,
            gif_msg.message_id,
            timer_msg.message_id,
        ]
        for mid in cleanup_ids:
            try:
                await context.bot.delete_message(
                    chat_id=update.effective_chat.id, message_id=mid
                )
            except Exception as e:
                logging.debug("Could not delete %s: %s", mid, e)

        context.user_data["stage"] = "period"
        next_msg = await update.message.reply_text(
            "Enter period number for prediction:",
            reply_markup=period_keyboard,
        )
        context.user_data["session_msgs"] = [next_msg.message_id]
        return

    await update.message.reply_text(
        "Tap the Wingo Prediction button to begin.",
        reply_markup=main_keyboard,
    )


app = ApplicationBuilder().token(TOKEN).build()
app.add_handler(CommandHandler("start", start))
app.add_handler(MessageHandler(filters.Regex(f"^{WINGO_BUTTON}$"), wingo))
app.add_handler(
    MessageHandler(filters.Regex(f"^({DURATION_30}|{DURATION_1M})$"), duration_chosen)
)
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

app.run_polling(drop_pending_updates=True)
